SomeWebApplication/SomeWebApplication/Controllers/AuthorController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SomeWebApplication.Models;
using SomeWebApplication.Models.ViewModels;

namespace SomeWebApplication.Controllers
{
    public class AuthorController : Controller
    {

        private readonly ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Author
        public ActionResult Index(string authorId)
        {
            if (String.IsNullOrEmpty(authorId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = _context.Users
                .Include(u => u.Books.Select(b => b.Genres))
                .SingleOrDefault(u => u.Id == authorId);

            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(user);
        }

        [HttpGet]
        public ActionResult GetAvatar(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = _context.Users.Find(id);

            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            if (user.AvatarBytes == null)
            {
                string path = System.IO.Path.Combine(Server.MapPath("~/"), "noavatar.png");
                return File(System.IO.File.ReadAllBytes(path), "image");
            }

            return File(_context.Users.Find(id).AvatarBytes, "image");
        }

        [HttpGet]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult SetAvatar(string id)
        {
            var user = _context.Users.Find(id);
            return View(user);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult SetAvatar(AuthorDetailsViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var user = _context.Users.Find(User.Identity.GetUserId());

            if (user == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            user.AvatarBytes = PostedFileHelper.GetBytesOfHttpPostedFile(model.AvatarFile);

            _context.Entry(user).State = EntityState.Modified;
            _context.SaveChanges();

            return View(user.Id);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && _context != null)
            {
                _context.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

SomeWebApplication/SomeWebApplication/Controllers/BookController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Data.Entity;
using Microsoft.AspNet.Identity;
using SomeWebApplication.Models;
using SomeWebApplication.Models.ViewModels;

namespace SomeWebApplication.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Book
        public ActionResult Index(int? bookId)
        {
            if (bookId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var book = _context.Books
                .Include(b => b.Genres)
                .Include(b => b.ApplicationUsers)
                .SingleOrDefault(b => b.Id == bookId);

            if (book == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(book);
        }

        [Authorize]
        [HttpGet]
        public ActionResult CreateBook()
        {
            var model = new CreateBookViewModel
            {
                Genres = new MultiSelectList(_context.Genres, "Id", "Name")
            };

            return View(model);
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult CreateBook(CreateBookViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Genres = new MultiSelectList(_context.Genres, "Id", "Name");
                return View(model);
            }

            Book book = new Book
            {
                Title = model.Title,
                Annotation = model.Annotation,
                Text = PostedFileHelper.GetFileContentFromBytes(PostedFileHelper.GetBytesOfHttpPostedFile(model.TextFile)),
                CoverBytes = PostedFileHelper.GetBytesOfHttpPostedFile(model.CoverFile),
                Status = "Finished",
                TimeStamp = DateTime.Now
            };

            string userId = User.Identity.GetUserId();
            var user = _context.Users.Find(userId);

            if (!String.IsNullOrEmpty(model.Authors))
            {
                foreach (var au in model.Authors.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries))
                {
                    var couser = _context.Users.SingleOrDefault(u => u.UserName == au);
                    if (couser == null) continue;
                    book.ApplicationUsers.Add(couser);
                }
            }

            book.ApplicationUsers.Add(user);

            foreach (var id in model.GenreIds)
            {
                var genre = _context.Genres.Find(id);
                book.Genres.Add(genre);
            }

            _context.Books.Add(book);
            _context.SaveChanges();

            return View("CreateBookSuccess", book);
        }

        public int GetBookRatingJson(int bookId)
        {
            var bookRating = _context.BookRatings
               .Include(cr => cr.FivePointRating)
               .Where(cr => cr.BookId == bookId)
               .ToList();

            return bookRating.Sum(cr => (int)cr.FivePointRating.Rating);
        }

        public void RateBook(int bookId, string ratingTypeString)
        {
            var userId = User.Identity.GetUserId();
            var rating = (FivePointRatingEnum)Enum.Parse(typeof(FivePointRatingEnum), ratingTypeString);


            var q = new FivePointRating { Rating = rating };
            var rate = new BookRating { BookId = bookId, FivePointRating = q, UserId = userId };

            _context.BookRatings.Add(rate);
            _context.SaveChanges();
        }


        [HttpGet]
        public ActionResult LeaveComment()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult LeaveComment(CommentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var comment = new Comment
            {
                BookId = model.BookId,
                UserId = User.Identity.GetUserId(),
                Text = model.Text,
                TimeStamp = DateTime.Now
            };

            _context.Comments.Add(comment);
            _context.SaveChanges();

            return RedirectToAction("Index", new { bookId = model.BookId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && _context != null)
            {
                _context.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

SomeWebApplication/SomeWebApplication/Controllers/GenreController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Data.Entity;
using PagedList;
using SomeWebApplication.Models;

namespace SomeWebApplication.Controllers
{
    public class GenreController : Controller
    {
        private readonly ApplicationDbContext _context = new ApplicationDbContext();
        private int _pageSize = 2;

        // GET: Genre
        public ActionResult Index(int? genreId, int? page)
        {
            if (genreId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            int pageNumber = (page ?? 1);

            ViewBag.GenreName = _context.Genres.Where(g => g.Id == genreId).FirstOrDefault().Name;
            ViewBag.GenreId = _context.Genres.Where(g => g.Id == genreId).FirstOrDefault().Id.ToString();
            var books = from b in _context.Books
                            .Include(b => b.Genres)
                            .Include(b => b.ApplicationUsers)
                        where b.Genres.FirstOrDefault(g => g.Id == genreId) != null
                        orderby b.Id
                        select b;

            return View(books.ToPagedList(pageNumber, _pageSize));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && _context != null)
            {
                _context.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

SomeWebApplication/SomeWebApplication/Controllers/ImageController.cs
using System.Web.Mvc;
using SomeWebApplication.Models;

namespace SomeWebApplication.Controllers
{
    public class ImageController : Controller
    {

        private readonly ApplicationDbContext _context = new ApplicationDbContext();

        // GET: Image
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetImage(int id)
        {
            return File(_context.Books.Find(id).CoverBytes, "image");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && _context != null)
            {
                _context.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

SomeWebApplication/SomeWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title – приложение ASP.NET</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js'></script>

    <link href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>

    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />

    <script type="text/javascript" src="~/Scripts/QScripts/date.js"></script>

    <link href="~/Content/Styles/CommentsBlock.css" rel="stylesheet" />
    <link href="~/Content/Styles/SomeStyles.css" rel="stylesheet" />
    <link href="~/Content/Styles/BookItem.css" rel="stylesheet" />

    @using Microsoft.AspNet.Identity;

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Search", "Index", "Search")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Add Book", "CreateBook", "Book")</li>
                    }
                </ul>

                <a href="@Url.Action("Index", "Author", new { authorId = User.Identity.GetUserId() })">
                    <img class="img-circle" style="width:40px;" src="@Url.Action("GetAvatar", "Author", new { id = User.Identity.GetUserId()})" alt="Alternate Text" />
                </a>

                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")


    @RenderSection("scripts", required: false)

    <script type="text/javascript" src="~/Scripts/bootstrap-select.min.js"></script>
    <link href="~/Content/bootstrap-select.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-select.css.map" rel="stylesheet" />

    <script type="text/javascript" src="~/Scripts/QScripts/inputImageLoader.js"></script>


    <link href="~/Content/Styles/EditsBoostrapPicker.css" rel="stylesheet" />
    <link href="~/Content/Styles/SomeStyles.css" rel="stylesheet" />
    <link href="~/Content/Styles/Just.css" rel="stylesheet" />

</body>
</html>

SomeWebApplication/SomeWebApplication/Views/Shared/_PartialPageBook.cshtml

@model SomeWebApplication.Models.Book


<div class="books-container">
    <div class="books-container__item-cover">
        <img src="@Url.Action("GetImage", "Image", new { id = Model.Id })" alt="Alternate Text" />
    </div>
    <div class="books-container__item-details">
        <h2>@Html.ActionLink(Model.Title, "Index", "Book", new { bookId = Model.Id }, new { })</h2>
        <div class="description">
            <p>@Model.Annotation</p>
        </div>
        <div>
            <ul class="books-container__item-meta">
                <li><span>Status:</span><span>@Model.Status</span></li>
                <li>
                    <span>Genres:</span>
                    <span>
                        @foreach (var genre in Model.Genres)
                        {
                            <a href="@Url.Action("Index", "Genre", new { genreId=genre.Id })">@genre.Name, </a>
                        }
                    </span>
                </li>
                <li>
                    <span>Author:</span>
                    <span>
                        @foreach (var au in Model.ApplicationUsers)
                        {
                            <a href="@Url.Action("Index", "Author", new { authorId=au.Id })">@au.UserName, </a>
                        }
                    </span>
                </li>
                <li><span>Date:</span><span>@Model.TimeStamp.ToShortDateString()</span></li>
            </ul>
        </div>
    </div>
</div>